version: "3"
services:
   dbmysql:
          image: mysql/mysql-server
          environment: 
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=orderapi
          ports: 
            - "3306:3306"
          volumes:
            - /db_data:/var/lib/mysql
   order-api:        
          image: orderapi
          restart: on-failure
          links:
            - "dbmysql:dbmysql"
          depends_on:
            dbmysql:
              condition: service_healthy
          ports:
            - "8080:8080"
