version: "3.5"
services:
   dbmysql:
          image: mysql/mysql-server:5.7.31
          environment: 
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=orderapi
          networks:
            - net-backend            
          expose:
            - "3306"  
   order-api:        
          image: orderapi
          depends_on:
            - dbmysql
          ports:
            - 8080:8080
          networks:
            - net-backend            
          environment: 
             DATABASE_HOST: dbmysql
             DATABASE_USER: root
             DATABASE_NAME: orderapi
             DATABASE_PORT: 3306 

networks:
  net-backend:



