version: "3.5"
services:
   dbmysql:
          image: mysql/mysql-server:5.7.31
          environment: 
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=orderapi
          networks:
            - net-backend            
          expose:
            - "3306"  
   dbsqlserver:
          image: "mcr.microsoft.com/mssql/server:2019-latest"
          networks:
            - net-backend            
          environment:
            SA_PASSWORD: "Mau123&&&"
            ACCEPT_EULA: "Y"            
   dbmongouser:
          image: mongo
          networks:
            - net-backend  
          ports:
            - "27017:27017"                      
          expose:
            - "27017"  
   order-api:        
          image: orderapi
          restart: on-failure
          depends_on:
            - dbmysql
          ports:
            - 8080:8080
          networks:
            - net-backend            
          environment: 
             DATABASE_HOST: dbmysql
             DATABASE_USER: root
             DATABASE_NAME: orderapi
             DATABASE_PORT: 3306 
   product-api:        
          image: salesproductapi
          restart: on-failure
          depends_on:
            - dbsqlserver
          ports:
            - 8087:80
          networks:
            - net-backend            
          environment: 
             DATABASE_HOST: dbsqlserver
             DATABASE_USER: sa
             DATABASE_NAME: productApi
             DATABASE_PORT: 1433 
   user-api:        
          image: salesapiusernode
          restart: on-failure
          depends_on:
            - dbmongouser
          ports:
            - 8088:8088
          networks:
            - net-backend            
   web-order:        
          image: salesorderfrontend
          restart: on-failure
          depends_on:
            - order-api
            - product-api
          ports:
            - 8086:80
          networks:
            - net-backend            
   web-product:        
          image: salesproductfrontend
          restart: on-failure
          depends_on:
            - product-api
          ports:
            - 8085:80
          networks:
            - net-backend            
   web-user:        
          image: salesuserreact
          restart: on-failure
          build:
            context: ../../reactjs/salesuser/
            dockerfile: Dockerfile
          depends_on:
            - user-api
          ports:
            - 3000:3000
          networks:
            - net-backend

networks:
  net-backend:



